databases:
  - name: movies-db
    databaseName: movies_db
    user: movies_user

services:
  - type: web
    name: mmdb-backend
    env: python
    runtime: python-3.11.9
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python init_db.py && gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movies-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: TMDB_API_KEY
        sync: false # You'll need to set this manually in Render dashboard

  - type: web
    name: mmdb-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build && echo 'Build completed, checking files:' && ls -la dist/ && echo 'Checking _redirects:' && test -f dist/_redirects && cat dist/_redirects || echo '_redirects file not found'"
    staticPublishPath: "./frontend/dist"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
